export const ADD_CATALOG_SUCCESS = 'ADD_PRODUCTS_SUCCESS';
export const ADD_CATALOG_REQUEST = 'ADD_PRODUCTS_REQUEST';
export const ADD_CATALOG_ERROR = 'ADD_PRODUCTS_ERROR';

export const ADD_HIT_SUCCESS = 'ADD_HIT_SUCCESS';
export const ADD_HIT_REQUEST = 'ADD_HIT_REQUEST';
export const ADD_HIT_ERROR = 'ADD_HIT_ERROR';

export const ADD_CATEGORIES_SUCCESS = 'ADD_CATEGORIES_SUCCESS';
export const ADD_CATEGORIES_REQUEST = 'ADD_CATEGORIES_REQUEST';
export const ADD_CATEGORIES_ERROR = 'ADD_CATEGORIES_ERROR';

export const ADD_NEXT_ITEMS_SUCCESS = 'ADD_NEXT_ITEMS_SUCCESS';
export const ADD_NEXT_ITEMS_REQUEST = 'ADD_NEXT_ITEMS_REQUEST';
export const ADD_NEXT_ITEMS_ERROR = 'ADD_NEXT_ITEMS_ERROR'

export const FETCH_CATEGORY_ITMES_SUCCSESS = 'FETCH_CATEGORY_ITMES_SUCCESS';
export const FETCH_CATEGORY_ITMES_REQUEST = 'FETCH_CATEGORY_ITMES_REQUEST';
export const FETCH_CATEGORY_ITMES_ERROR = 'FETCH_CATEGORY_ITMES_ERROR';

export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_REDIRECT_SEARCH = 'SET_REDIRECT_SEARCH';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_CART_QUANTITY = 'SET_CART_QUANTITY';
export const REDIRECT_TO_CART = 'REDIRECT_TO_CART';

export const SET_ITEM_LOCALSTORAGE = 'SET_ITEM_LOCALSTORAGE';
export const GET_ITEM_LOCALSTORAGE = 'GET_ITEM_LOCALSTORAGE';
export const CLEAR_LOCALSTORAGE = 'CLEAR_LOCALSTORAGE';
export const REMOVE_ITEM_LOCALSTORAGE = 'REMOVE_ITEM_LOCALSTORAGE';
